server:
  port: 9001

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

user:
  service:
    message: "User Service Config Loaded from Config Server"

logging:
  level:
    root: INFO
